[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
temple = "81BWs7RGtN2EEvaGWZe8EQ8nhswHTHVzYUn5iPFoRr9o"

[registry]
url = "https://api.apr.dev"
[scripts]
test = "npx mocha --require tsx --recursive tests/*.test.ts"

# 单独运行某些测试文件
temple-init = "npx mocha --require tsx tests/temple-init.test.ts"
incense-init = "npx mocha --require tsx tests/incense-init.test.ts"
user-init = "npx mocha --require tsx tests/user-init.test.ts"
incense-buy = "npx mocha --require tsx tests/incense-buy.test.ts"
incense-burn = "npx mocha --require tsx tests/incense-burn.test.ts"
draw-fortune = "npx mocha --require tsx tests/draw-fortune.test.ts"
wish = "npx mocha --require tsx tests/wish.test.ts"
donation = "npx mocha --require tsx tests/donation.test.ts"

[provider]
cluster = "http://localhost:8899"
wallet = "~/.config/solana/id.json"

[test]
validator = { url = "http://localhost:8899" }
startup_wait = 10000
