[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solji_program = "EHeMFMeN22VbNmB9BnPaQLRFVVGRuw5uEU6bVSM3eWaw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
api = "yarn run ts-node example/index.ts"
donate = "yarn run ts-node example/donate.ts"
draw = "yarn run ts-node example/draw.ts"
mint = "yarn run ts-node example/mint.ts"
temple = "yarn run ts-node example/temple.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
wish = "yarn run ts-node example/wish.ts"
